---
- hosts: localhost
  vars:
    level: level00
  tasks:
    - name: create user
      user:
        name: "{{ level }}"
        password: $5$oDfglsSRA.ojUUDY$SRlh.ti7Y/U8.ibkGWuelptkdOzhmrcI4mvcAV0NdAD
        shell: /bin/bash

    - name: set user home directory permissions
      file:
        path: "/home/{{ level }}"
        mode: 0700

    - name: copy instructions, hints and solution
      copy:
        src:  "challenges/{{ level }}/docs"
        dest: "/home/{{ level }}"
        group: "{{ level }}"
        owner: "{{ level }}"
        mode: 0400
