---
- hosts: localhost
  vars:
    level: level00
    homedir: "/home/{{ level }}"
  tasks:
    - name: create user
      user:
        name: "{{ level }}"
        password: $5$oDfglsSRA.ojUUDY$SRlh.ti7Y/U8.ibkGWuelptkdOzhmrcI4mvcAV0NdAD
        shell: /bin/bash

    - name: set user home directory permissions
      file:
        path: "{{ homedir }}"
        mode: 0700

    - name: copy instructions, hints and solution
      copy:
        src:  "challenges/{{ level }}/docs"
        dest: "{{ homedir }}"
        group: "{{ level }}"
        owner: "{{ level }}"
        mode: 0400

    - name: present instructions when logging into level
      lineinfile:
        path: "{{ homedir }}/.bashrc"
        insertafter: EOF
        line: "cat {{ homedir }}/docs/instructions"
