---
- hosts: all
  gather_facts: no
  become: true
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  tasks:
    - name: update apt cache
      apt:
          update_cache: yes

    - name: install mdless
      block:
        - name: install ruby
          apt:
            name: ruby

        - name: install mdless
          shell: "gem install mdless"

    - name: add an entry to /etc/hosts
      lineinfile:
        path: "/etc/hosts"
        insertafter: EOF
        line: "127.0.0.1       wargame"

    - name: create the group leveluser to apply security policies to all levels
      group:
        name: leveluser
        state: present

    - name: create a directory to hold services
      file:
        path: /service/
        state: directory
        owner: root
        group: root
        mode: 0711

    - include_role:
        name: level
      vars:
        homedir: "/home/{{ level }}"
      loop:
        - level00
        - level01
        - intropwntools
      loop_control:
        loop_var: level
        index_var: level_num

    - include_role:
        name: harden
