---
- hosts: localhost
  tasks:
    - include_role:
        name: level
      vars:
        homedir: "/home/{{ level }}"
      loop:
        - level00
        - level01
      loop_control:
        loop_var: level
