---
- hosts: all
  gather_facts: no
  become: true
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  tasks:
    - name: Update APT Cache
      apt:
          update_cache: yes
    - include_role:
        name: level
      vars:
        homedir: "/home/{{ level }}"
      loop:
        - level00
        - level01
        - introstrings
      loop_control:
        loop_var: level
        index_var: level_num
    - include_role:
        name: harden

