---
- hosts: all
  gather_facts: no
  become: true
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get update && sudo apt-get -y install python-simplejson
  tasks:
    - name: update apt cache
      apt:
          update_cache: yes

    - name: install mdless
      block:
        - name: install ruby
          apt:
            name: ruby

        - name: install mdless
          shell: "gem install mdless"

    - name: add an entry to /etc/hosts
      lineinfile:
        path: "/etc/hosts"
        insertafter: EOF
        line: "127.0.0.1       wargame"

    - name: create the group leveluser to apply security policies to all levels
      group:
        name: leveluser
        state: present

    - name: allow passworded ssh logins
      block:
        - name: enable passworded ssh in config
          replace:
            path: "/etc/ssh/sshd_config"
            regexp: "PasswordAuthentication no"
            replace: "PasswordAuthentication yes"
        - name: restart ssh
          service:
            name: ssh
            state: restarted

    - name: create a directory to hold services
      file:
        path: /service/
        state: directory
        owner: root
        group: root
        mode: 0711

    - name: install gef
      block:
        - name: remove gef sources
          file:
            state: absent
            path: "/service/gef"
        - name: get gef sources
          git:
            repo: https://github.com/hugsy/gef.git
            dest: /service/gef

    - name: set an initial cur_password fact
      set_fact:
        cur_password: "wargame"

    - name: set the list of levels to generate
      set_fact:
        levels_list:
          - introduction
          - introstrings
          - introtempdir
          - introexfil
          - intronc
          - intropwntools
          - babyxor
          - babyre
          - babyrsa
          - babypwn
          - root

    - include_role:
        name: level
      vars:
        homedir: "/home/{{ level_tuple.1 }}"
        level: "{{ level_tuple.1 }}"
      with_indexed_items: "{{ levels_list }}"
      loop_control:
        loop_var: level_tuple
        index_var: level_num

    - include_role:
        name: harden
