- name: create level
  block:
    - name: lookup password from password file
      set_fact: "{{ level }}_password={{ lookup('file', 'challenges/{{ level }}/src/password') }}"

    - name: check for next level password file
      local_action: stat path="challenges/level0{{ level_num + 1 }}/src/password"
      register: next_level_password_file

    - name: define levelXX_flag variable - i.e. password for next level
      set_fact: "{{ level }}_flag={{ lookup('file', 'challenges/level0{{ level_num + 1 }}/src/password')}}"
      when: next_level_password_file.stat.exists

    - name: encrypt password
      shell: "echo {{ vars[level + '_password'] | quote }} | openssl passwd -1 -stdin"
      register: encypted_password

    - name: create user
      user:
        name: "{{ level }}"
        password: "{{ encypted_password.stdout }}"
        shell: /bin/bash
    - name: set homedir permissions
      file:
        path: "{{ homedir }}"
        mode: 0700

- name: copy instructions, hints and solution
  copy:
    src:  "challenges/{{ level }}/docs"
    dest: "{{ homedir }}"
    group: "{{ level }}"
    owner: "{{ level }}"
    mode: 0400

- name: present instructions when logging into level
  lineinfile:
    path: "{{ homedir }}/.bashrc"
    insertafter: EOF
    line: "{{ item }}"
  with_items:
    - cd "{{ homedir }}"
    - clear
    - cat "{{ homedir }}/docs/instructions"

- name: run level specific playbook
  import_tasks: "challenges/{{ level }}/setup.yml"
