- name: create level
  block:
    - name: lookup password from password file
      set_fact: "{{ level }}_password={{ lookup('file', 'challenges/{{ level }}/src/password') }}"

    - name: check for next level password file
      become: false
      local_action: stat path="{{ 'challenges/level%02d/src/password' | format(level_num + 1) }}"
      register: next_level_password_file

    - name: define levelXX_flag variable - i.e. password for next level
      set_fact: "{{ level }}_flag={{ lookup('file', '{{ next_level_password_file.stat.path }}' )}}"
      when: next_level_password_file.stat.exists

    - name: encrypt password
      shell: "echo {{ vars[level + '_password'] | quote }} | openssl passwd -1 -stdin"
      register: encypted_password

    - name: create user
      user:
        name: "{{ level }}"
        password: "{{ encypted_password.stdout }}"
        shell: /bin/bash

- name: copy instructions, hints and solution
  copy:
    src:  "challenges/{{ level }}/docs"
    dest: "{{ homedir }}"
    group: "{{ level }}"
    owner: "{{ level }}"
    mode: 0400

- name: present instructions when logging into level
  lineinfile:
    path: "{{ homedir }}/.bashrc"
    insertafter: EOF
    line: "{{ item }}"
  with_items:
    - clear
    - alias instructions='mdless "{{ homedir }}"/docs/instructions.md'
    - alias hints='mdless "{{ homedir }}"/docs/hints.md'
    - alias solution='mdless "{{ homedir }}"/docs/solution.md'
    - instructions

- name: set homedir permissions
  block:
    - name: tighten the permissions
      file:
        recurse: yes
        mode: 000
        path: "{{ homedir }}"
    - name: relax the permissions
      file:
        recurse: yes
        owner: root
        group: "{{ level }}"
        path: "{{ homedir }}"
        mode: u=rwX,g=rX,o=

- name: run level specific playbook
  import_tasks: "challenges/{{ level }}/setup.yml"
