- name: prevent users from viewing process information.
  shell: mount -o remount,hidepid=2 /proc

- name: prevent users from viewing kernel debug messages
  shell: sysctl -w kernel.dmesg_restrict=1

- name: prevent users from viewing each other's solutions in the temp dirs
  file:
    path: "{{ item }}"
    mode: 01733
  with_items:
    - "/tmp"
    - "/var/tmp"
    - "/dev/shm"

- name: prevent resource exhaustion attacks
  lineinfile:
    path: "/etc/security/limits.conf"
    insertafter: EOF
    line: "@leveluser hard nproc 64"
